using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kartverket.Geonorge.Download.Models.V2
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.geonorge.no/SOSI/download/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("OrderReceipt", Namespace = "http://skjema.geonorge.no/SOSI/download/2.0", IsNullable = false)]
    public partial class OrderReceiptType
    {

        private string referenceNumberField;

        private FileType[] filesField;

        /// <remarks/>
        /// <summary>
        /// The order number generated by the system
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        /// <summary>
        /// The list of files returned from order. Polygon selection is sendt by email with link to download.
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable = false)]
        public FileType[] files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }
    }
}