//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Geonorge.NedlastingApi.V3 {
    using Newtonsoft.Json;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("Area", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class AreaType {
        
        private string typeField;
        
        private string nameField;
        
        private string codeField;
        
        private ProjectionType[] projectionsField;
        
        private FormatType[] formatsField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("projection", IsNullable=false)]
        public ProjectionType[] projections {
            get {
                return this.projectionsField;
            }
            set {
                this.projectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("format", IsNullable=false)]
        public FormatType[] formats {
            get {
                return this.formatsField;
            }
            set {
                this.formatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("Projection", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class ProjectionType {
        
        private string codeField;
        
        private string nameField;
        
        private string codespaceField;
        
        private FormatType[] formatsField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string codespace {
            get {
                return this.codespaceField;
            }
            set {
                this.codespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("format", IsNullable=false)]
        public FormatType[] formats {
            get {
                return this.formatsField;
            }
            set {
                this.formatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("Format", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class FormatType {
        
        private string nameField;
        
        private string versionField;
        
        private ProjectionType[] projectionsField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("projection", IsNullable=false)]
        public ProjectionType[] projections {
            get {
                return this.projectionsField;
            }
            set {
                this.projectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kxml.no/rest/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Link", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
    public partial class LinkType {
        
        private string hrefField;
        
        private string relField;
        
        private bool templatedField;
        
        private bool templatedFieldSpecified;
        
        private string typeField;
        
        private string deprecationField;
        
        private string nameField;
        
        private string titleField;
        
        /// <remarks/>
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        public string rel {
            get {
                return this.relField;
            }
            set {
                this.relField = value;
            }
        }
        
        /// <remarks/>
        public bool templated {
            get {
                return this.templatedField;
            }
            set {
                this.templatedField = value;
            }
        }
        
        /// <remarks/>
        [JsonIgnore]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool templatedSpecified {
            get {
                return this.templatedFieldSpecified;
            }
            set {
                this.templatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string deprecation {
            get {
                return this.deprecationField;
            }
            set {
                this.deprecationField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("CanDownloadRequest", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class CanDownloadRequestType {
        
        private string metadataUuidField;
        
        private string coordinatesField;
        
        private string coordinateSystemField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string metadataUuid {
            get {
                return this.metadataUuidField;
            }
            set {
                this.metadataUuidField = value;
            }
        }
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        public string coordinateSystem {
            get {
                return this.coordinateSystemField;
            }
            set {
                this.coordinateSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("CanDownloadResponse", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class CanDownloadResponseType {
        
        private bool canDownloadField;
        
        private string messageField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public bool canDownload {
            get {
                return this.canDownloadField;
            }
            set {
                this.canDownloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("Capabilities", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class CapabilitiesType {
        
        private bool supportsProjectionSelectionField;
        
        private bool supportsFormatSelectionField;
        
        private bool supportsPolygonSelectionField;
        
        private bool supportsAreaSelectionField;
        
        private string mapSelectionLayerField;
        
        private bool supportsDownloadBundlingField;
        
        private string distributedByField;
        
        private string accessConstraintRequiredRoleField;
        
        private bool deliveryNotificationByEmailField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public bool supportsProjectionSelection {
            get {
                return this.supportsProjectionSelectionField;
            }
            set {
                this.supportsProjectionSelectionField = value;
            }
        }
        
        /// <remarks/>
        public bool supportsFormatSelection {
            get {
                return this.supportsFormatSelectionField;
            }
            set {
                this.supportsFormatSelectionField = value;
            }
        }
        
        /// <remarks/>
        public bool supportsPolygonSelection {
            get {
                return this.supportsPolygonSelectionField;
            }
            set {
                this.supportsPolygonSelectionField = value;
            }
        }
        
        /// <remarks/>
        public bool supportsAreaSelection {
            get {
                return this.supportsAreaSelectionField;
            }
            set {
                this.supportsAreaSelectionField = value;
            }
        }
        
        /// <remarks/>
        public string mapSelectionLayer {
            get {
                return this.mapSelectionLayerField;
            }
            set {
                this.mapSelectionLayerField = value;
            }
        }
        
        /// <remarks/>
        public bool supportsDownloadBundling {
            get {
                return this.supportsDownloadBundlingField;
            }
            set {
                this.supportsDownloadBundlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string distributedBy {
            get {
                return this.distributedByField;
            }
            set {
                this.distributedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accessConstraintRequiredRole {
            get {
                return this.accessConstraintRequiredRoleField;
            }
            set {
                this.accessConstraintRequiredRoleField = value;
            }
        }
        
        /// <remarks/>
        public bool deliveryNotificationByEmail {
            get {
                return this.deliveryNotificationByEmailField;
            }
            set {
                this.deliveryNotificationByEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("DownloadUsageEntry", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class DownloadUsageEntryType {
        
        private string metadataUuidField;
        
        private string areaCodeField;
        
        private string areaNameField;
        
        private string formatField;
        
        private string projectionField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string metadataUuid {
            get {
                return this.metadataUuidField;
            }
            set {
                this.metadataUuidField = value;
            }
        }
        
        /// <remarks/>
        public string areaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string areaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
            }
        }
        
        /// <remarks/>
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string projection {
            get {
                return this.projectionField;
            }
            set {
                this.projectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("DownloadUsageRequest", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class DownloadUsageRequestType {
        
        private string groupField;
        
        private string[] purposeField;
        
        private string softwareClientField;
        
        private string softwareClientVersionField;
        
        private DownloadUsageEntryType[] entriesField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("purpose")]
        public string[] purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        /// <remarks/>
        public string softwareClient {
            get {
                return this.softwareClientField;
            }
            set {
                this.softwareClientField = value;
            }
        }
        
        /// <remarks/>
        public string softwareClientVersion {
            get {
                return this.softwareClientVersionField;
            }
            set {
                this.softwareClientVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("downloadusageentry", IsNullable=false)]
        public DownloadUsageEntryType[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("File", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class FileType {
        
        private string downloadUrlField;
        
        private string fileSizeField;
        
        private string nameField;
        
        private string fileIdField;
        
        private string metadataUuidField;
        
        private string areaField;
        
        private string coordinatesField;
        
        private string projectionField;
        
        private string formatField;
        
        private string statusField;
        
        private string metadataNameField;
        
        private string areaNameField;
        
        private string projectionNameField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string downloadUrl {
            get {
                return this.downloadUrlField;
            }
            set {
                this.downloadUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string metadataUuid {
            get {
                return this.metadataUuidField;
            }
            set {
                this.metadataUuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projection {
            get {
                return this.projectionField;
            }
            set {
                this.projectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string metadataName {
            get {
                return this.metadataNameField;
            }
            set {
                this.metadataNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string areaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectionName {
            get {
                return this.projectionNameField;
            }
            set {
                this.projectionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("Order", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class OrderType {
        
        private bool downloadAsBundleField;
        
        private string emailField;
        
        private string downloadBundleUrlField;
        
        private OrderLineType[] orderLinesField;
        
        private string usageGroupField;
        
        private string softwareClientField;
        
        private string softwareClientVersionField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public bool downloadAsBundle {
            get {
                return this.downloadAsBundleField;
            }
            set {
                this.downloadAsBundleField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string downloadBundleUrl {
            get {
                return this.downloadBundleUrlField;
            }
            set {
                this.downloadBundleUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("orderline", IsNullable=false)]
        public OrderLineType[] orderLines {
            get {
                return this.orderLinesField;
            }
            set {
                this.orderLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usageGroup {
            get {
                return this.usageGroupField;
            }
            set {
                this.usageGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string softwareClient {
            get {
                return this.softwareClientField;
            }
            set {
                this.softwareClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string softwareClientVersion {
            get {
                return this.softwareClientVersionField;
            }
            set {
                this.softwareClientVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("OrderLine", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class OrderLineType {
        
        private OrderAreaType[] areasField;
        
        private FormatType[] formatsField;
        
        private string metadataUuidField;
        
        private ProjectionType[] projectionsField;
        
        private string coordinatesField;
        
        private string coordinatesystemField;
        
        private string clipperFileField;
        
        private string[] usagePurposeField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("orderarea", IsNullable=false)]
        public OrderAreaType[] areas {
            get {
                return this.areasField;
            }
            set {
                this.areasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("format", IsNullable=false)]
        public FormatType[] formats {
            get {
                return this.formatsField;
            }
            set {
                this.formatsField = value;
            }
        }
        
        /// <remarks/>
        public string metadataUuid {
            get {
                return this.metadataUuidField;
            }
            set {
                this.metadataUuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("projection", IsNullable=false)]
        public ProjectionType[] projections {
            get {
                return this.projectionsField;
            }
            set {
                this.projectionsField = value;
            }
        }
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        public string coordinatesystem {
            get {
                return this.coordinatesystemField;
            }
            set {
                this.coordinatesystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clipperFile {
            get {
                return this.clipperFileField;
            }
            set {
                this.clipperFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usagePurpose", IsNullable=true)]
        public string[] usagePurpose {
            get {
                return this.usagePurposeField;
            }
            set {
                this.usagePurposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("OrderArea", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class OrderAreaType {
        
        private string codeField;
        
        private string nameField;
        
        private string typeField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("OrderReceipt", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class OrderReceiptType {
        
        private string referenceNumberField;
        
        private FileType[] filesField;
        
        private string emailField;
        
        private System.DateTime orderDateField;
        
        private bool downloadAsBundleField;
        
        private string downloadBundleUrlField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
        public FileType[] files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime orderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public bool downloadAsBundle {
            get {
                return this.downloadAsBundleField;
            }
            set {
                this.downloadAsBundleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string downloadBundleUrl {
            get {
                return this.downloadBundleUrlField;
            }
            set {
                this.downloadBundleUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("VersionResponse", Namespace="http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/3.0", IsNullable=false)]
    public partial class VersionResponseType {
        
        private string versionField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kxml.no/rest/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("LinkListe", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
    public partial class LinkListeType {
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_links")]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
}
