// <auto-generated />
namespace Kartverket.Geonorge.Download.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDownloadUsage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDownloadUsage));
        
        string IMigrationMetadata.Id
        {
            get { return "201810220856029_AddDownloadUsage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
