// <auto-generated />
namespace Kartverket.Geonorge.Download.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class SupportsPolygonSelectionRequiredRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SupportsPolygonSelectionRequiredRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041359577_SupportsPolygonSelectionRequiredRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
