// <auto-generated />
namespace Kartverket.Geonorge.Download.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddClipperFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClipperFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202202030742406_AddClipperFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
