// <auto-generated />
using System;
using Geonorge.Download.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Geonorge.Download.Migrations
{
    [DbContext(typeof(DownloadContext))]
    [Migration("20250930104737_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Danish_Norwegian_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Geonorge.Download.Models.ClipperFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ClipperFiles");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessConstraint")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AccessConstraint");

                    b.Property<string>("AccessConstraintRequiredRole")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AccessConstraintRequiredRole");

                    b.Property<string>("FmeClippingUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fmeklippeUrl");

                    b.Property<string>("MapSelectionLayer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mapSelectionLayer");

                    b.Property<int>("MaxArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maxArea")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MetadataUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("metadataUuid");

                    b.Property<bool?>("SupportsAreaSelection")
                        .HasColumnType("bit")
                        .HasColumnName("supportsAreaSelection");

                    b.Property<bool?>("SupportsFormatSelection")
                        .HasColumnType("bit")
                        .HasColumnName("supportsFormatSelection");

                    b.Property<bool?>("SupportsPolygonSelection")
                        .HasColumnType("bit")
                        .HasColumnName("supportsPolygonSelection");

                    b.Property<bool?>("SupportsProjectionSelection")
                        .HasColumnType("bit")
                        .HasColumnName("supportsProjectionSelection");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Tittel");

                    b.HasKey("Id");

                    b.HasIndex("MetadataUuid");

                    b.ToTable("Dataset");
                });

            modelBuilder.Entity("Geonorge.Download.Models.DownloadUsageEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeAsStrings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Purpose");

                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("CAST('00000000-0000-0000-0000-000000000000' AS uniqueidentifier)");

                    b.Property<string>("SoftwareClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareClientVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DownloadUsage");
                });

            modelBuilder.Entity("Geonorge.Download.Models.File", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccessConstraintRequiredRole")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AccessConstraintRequiredRole");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kategori");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int")
                        .HasColumnName("dataset");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inndeling");

                    b.Property<string>("DivisionKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("inndelingsverdi");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("filnavn")
                        .HasColumnOrder(0);

                    b.Property<string>("Format")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("format");

                    b.Property<string>("Projection")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("projeksjon");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("underkategori");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("url")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Division");

                    b.HasIndex("DivisionKey");

                    b.HasIndex("Format");

                    b.HasIndex("Projection");

                    b.ToTable("filliste");
                });

            modelBuilder.Entity("Geonorge.Download.Models.MachineAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Passsword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("MachineAccounts");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Order", b =>
                {
                    b.Property<int>("referenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("referenceNumber");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("referenceNumber"), 1000L);

                    b.Property<bool>("DownloadAsBundle")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DownloadBundleNotificationSent")
                        .HasColumnType("datetime");

                    b.Property<string>("DownloadBundleUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("CAST('00000000-0000-0000-0000-000000000000' AS uniqueidentifier)");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<DateTime?>("orderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("referenceNumber");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("IDX_Uuid");

                    b.ToTable("orderDownload");
                });

            modelBuilder.Entity("Geonorge.Download.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClipperFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordinateSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("downloadUrl");

                    b.Property<string>("FileName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("fileName");

                    b.Property<Guid?>("FileUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataUuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceNumber")
                        .HasColumnType("int")
                        .HasColumnName("referenceNumber");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("CAST('00000000-0000-0000-0000-000000000000' AS uniqueidentifier)");

                    b.HasKey("Id");

                    b.HasIndex("FileUuid")
                        .HasDatabaseName("IDX_FileUuid");

                    b.HasIndex("ReferenceNumber");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("IDX_Uuid");

                    b.ToTable("orderItem");
                });

            modelBuilder.Entity("Geonorge.Download.Models.File", b =>
                {
                    b.HasOne("Geonorge.Download.Models.Dataset", "Dataset")
                        .WithMany("filliste")
                        .HasForeignKey("DatasetId");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Geonorge.Download.Models.OrderItem", b =>
                {
                    b.HasOne("Geonorge.Download.Models.Order", "Order")
                        .WithMany("orderItem")
                        .HasForeignKey("ReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Dataset", b =>
                {
                    b.Navigation("filliste");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Order", b =>
                {
                    b.Navigation("orderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
