// <auto-generated />
using System;
using Geonorge.Download.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Geonorge.Download.Migrations
{
    [DbContext(typeof(DownloadContext))]
    [Migration("20250625113647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Geonorge.Download.Models.ClipperFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ClipperFiles");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessConstraint")
                        .HasColumnType("text")
                        .HasColumnName("AccessConstraint");

                    b.Property<string>("AccessConstraintRequiredRole")
                        .HasColumnType("text")
                        .HasColumnName("AccessConstraintRequiredRole");

                    b.Property<string>("FmeClippingUrl")
                        .HasColumnType("text")
                        .HasColumnName("fmeklippeUrl");

                    b.Property<string>("MapSelectionLayer")
                        .HasColumnType("text")
                        .HasColumnName("mapSelectionLayer");

                    b.Property<int>("MaxArea")
                        .HasColumnType("integer")
                        .HasColumnName("maxArea");

                    b.Property<string>("MetadataUuid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("metadataUuid");

                    b.Property<bool?>("SupportsAreaSelection")
                        .HasColumnType("boolean")
                        .HasColumnName("supportsAreaSelection");

                    b.Property<bool?>("SupportsFormatSelection")
                        .HasColumnType("boolean")
                        .HasColumnName("supportsFormatSelection");

                    b.Property<bool?>("SupportsPolygonSelection")
                        .HasColumnType("boolean")
                        .HasColumnName("supportsPolygonSelection");

                    b.Property<bool?>("SupportsProjectionSelection")
                        .HasColumnType("boolean")
                        .HasColumnName("supportsProjectionSelection");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Tittel");

                    b.HasKey("Id");

                    b.HasIndex("MetadataUuid");

                    b.ToTable("Dataset");
                });

            modelBuilder.Entity("Geonorge.Download.Models.DownloadUsageEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaCode")
                        .HasColumnType("text");

                    b.Property<string>("AreaName")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("Projection")
                        .HasColumnType("text");

                    b.Property<string>("PurposeAsStrings")
                        .HasColumnType("text")
                        .HasColumnName("Purpose");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoftwareClient")
                        .HasColumnType("text");

                    b.Property<string>("SoftwareClientVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DownloadUsage");
                });

            modelBuilder.Entity("Geonorge.Download.Models.File", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessConstraintRequiredRole")
                        .HasColumnType("text")
                        .HasColumnName("AccessConstraintRequiredRole");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kategori");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("integer")
                        .HasColumnName("dataset");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inndeling");

                    b.Property<string>("DivisionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("inndelingsverdi");

                    b.Property<string>("Filename")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("filnavn")
                        .HasColumnOrder(0);

                    b.Property<string>("Format")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("format");

                    b.Property<string>("Projection")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projeksjon");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("underkategori");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Division");

                    b.HasIndex("DivisionKey");

                    b.HasIndex("Format");

                    b.HasIndex("Projection");

                    b.ToTable("filliste");
                });

            modelBuilder.Entity("Geonorge.Download.Models.MachineAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Passsword")
                        .HasColumnType("text");

                    b.Property<string>("Roles")
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("MachineAccounts");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Order", b =>
                {
                    b.Property<int>("referenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("referenceNumber");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("referenceNumber"));

                    b.Property<bool>("DownloadAsBundle")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DownloadBundleNotificationSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadBundleUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("orderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orderDate");

                    b.Property<string>("username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("referenceNumber");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("IDX_OrderUuid");

                    b.ToTable("orderDownload");
                });

            modelBuilder.Entity("Geonorge.Download.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("AreaName")
                        .HasColumnType("text");

                    b.Property<string>("ClipperFile")
                        .HasColumnType("text");

                    b.Property<string>("CoordinateSystem")
                        .HasColumnType("text");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<Guid?>("FileUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("MetadataName")
                        .HasColumnType("text");

                    b.Property<string>("MetadataUuid")
                        .HasColumnType("text");

                    b.Property<string>("Projection")
                        .HasColumnType("text");

                    b.Property<string>("ProjectionName")
                        .HasColumnType("text");

                    b.Property<int>("ReferenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileUuid")
                        .HasDatabaseName("IDX_FileUuid");

                    b.HasIndex("ReferenceNumber");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("IDX_OrderItemUuid");

                    b.ToTable("orderItem");
                });

            modelBuilder.Entity("Geonorge.Download.Models.File", b =>
                {
                    b.HasOne("Geonorge.Download.Models.Dataset", "Dataset")
                        .WithMany("filliste")
                        .HasForeignKey("DatasetId");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Geonorge.Download.Models.OrderItem", b =>
                {
                    b.HasOne("Geonorge.Download.Models.Order", "Order")
                        .WithMany("orderItem")
                        .HasForeignKey("ReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Dataset", b =>
                {
                    b.Navigation("filliste");
                });

            modelBuilder.Entity("Geonorge.Download.Models.Order", b =>
                {
                    b.Navigation("orderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
